export const projects = [
  { slug: "black-box-auditor", number: "01", title: "Black Box Auditor", eyebrow: "AI evaluation platform", summary: "A reproducible system for testing how model behavior changes when the same underlying request is phrased in different ways.", impact: "Turns an opaque model evaluation into an inspectable audit with comparable metrics, behavioral clusters, evidence, and portable reports.", metrics: [["7", "controlled prompt mutations"], ["12", "automated tests"], ["3", "export formats"]], stack: ["Python", "Streamlit", "scikit-learn", "Plotly", "GitHub Actions"], live: "https://abdi-blackbox-auditor.streamlit.app", github: "https://github.com/AbdiqafarOmar/BlackBox-Auditor" },
  { slug: "ecomind", number: "02", title: "EcoMind", eyebrow: "AI infrastructure analysis", summary: "A decision-support tool for exploring how model scale and infrastructure assumptions shape estimated training energy and carbon.", impact: "Makes infrastructure tradeoffs visible through configurable scenarios, batch analysis, sensitivity comparisons, and exportable reports.", metrics: [["500", "models per batch"], ["3", "scenario comparisons"], ["14", "automated tests"]], stack: ["Python", "Streamlit", "Pandas", "Plotly", "GitHub Actions"], live: "https://ecomind-carbon.streamlit.app", github: "https://github.com/AbdiqafarOmar/EcoMind" },
] as const;

export const experiences = [
  { role: "AI Automation Intern", company: "Great American Insurance Group", period: "May 2026 – Aug 2026", location: "Cincinnati, OH", intro: "Evaluated AI-assisted document pipelines for aviation and crop insurance, translating ambiguous business language into testable extraction behavior.", bullets: ["Built and validated field-level ground-truth datasets used to evaluate document extraction.", "Refined prompts for edge cases such as distinguishing passenger counts from crew-related values.", "Tested a UiPath email-ingestion workflow from shared-inbox routing through Orchestrator processing."], tags: ["AI evaluation", "Prompt engineering", "UiPath"] },
  { role: "Software Engineering Intern", company: "Duke Office of Information Technology · Code+", period: "May 2024 – Aug 2024", location: "Durham, NC", intro: "Built the core backend for a research-discovery product matching Duke faculty with funding and collaboration opportunities.", bullets: ["Created ingestion and semantic-retrieval workflows with Python, LangChain, and ChromaDB.", "Represented faculty profiles and opportunity records as embeddings for contextual similarity search.", "Continued improving and maintaining the platform after its initial summer development cycle."], tags: ["Python", "LangChain", "ChromaDB"] },
] as const;

export const skills = ["Python", "Java", "JavaScript", "React", "Next.js", "SQL", "LangChain", "ChromaDB", "Streamlit", "Git", "Docker", "Linux"] as const;
